name: bilingual_kids
description: A simple bilingual learning app for kids
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  audioplayers: ^6.5.1
  intl: ^0.18.0
  http: ^0.13.6
  flutter_svg: ^1.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/data/words.json
    - assets/data/alphabets_course.json
    - assets/images/
    - assets/images/alphabets/
    - assets/audio/
    - assets/audio/alphabets/
