name: bilingual_kids
description: A simple bilingual learning app for kids
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  audioplayers: ^2.0.2
  intl: ^0.18.0
  http: ^0.13.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/data/words.json
    - assets/images/
    - assets/audio/